package web

const cloudGraphTemplate = `{{define "content"}}
<div class="cloud-graph min-w-0 space-y-6">
    <header class="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
        <div>
            <p class="text-xs font-semibold uppercase tracking-[0.22em] text-[#2f6db5]">Relationship console</p>
            <h2 class="mt-2 text-4xl font-semibold tracking-tight text-slate-950">Cloud graph</h2>
            {{if .Context.Project}}<p class="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Project resources in <strong>{{.Context.Project.Name}}</strong>, organization policies, and every edge that connects them.</p>{{end}}
        </div>
        {{if and .Context.Project (eq .State "ready")}}
        <div class="flex flex-wrap gap-2">
            <button class="btn btn-secondary" hx-get="/projects/{{.Context.Project.Slug}}/cloud/new?kind=network" hx-target="#modal-content" hx-indicator="#cloud-loading">New network</button>
            <button class="btn btn-secondary" hx-get="/projects/{{.Context.Project.Slug}}/cloud/new?kind=disk" hx-target="#modal-content" hx-indicator="#cloud-loading">New disk</button>
            <button class="btn btn-primary" hx-get="/projects/{{.Context.Project.Slug}}/cloud/new?kind=load-balancer" hx-target="#modal-content" hx-indicator="#cloud-loading">New load balancer</button>
        </div>
        {{end}}
    </header>

    <div id="cloud-loading" class="htmx-indicator rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800" role="status">Loading the latest graph…</div>
    <div id="graph-error" role="alert" aria-live="assertive" aria-atomic="true"></div>

    {{if not .Context.Project}}
    <section class="console-card rounded-[28px] p-10 text-center">
        <h3 class="text-xl font-semibold">Create a project to map your cloud</h3>
        <p class="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Networks, subnets, instances, disks, and load balancers are project-scoped. Policies remain organization-scoped.</p>
        <button class="btn btn-primary mt-5" hx-get="/projects/new?redirect_to=/cloud" hx-target="#modal-content">Create project</button>
    </section>
    {{else if eq .State "error"}}
    <section role="alert" class="rounded-[28px] border border-red-200 bg-red-50 p-8">
        <p class="text-xs font-bold uppercase tracking-[0.2em] text-red-600">Graph unavailable</p>
        <h3 class="mt-2 text-xl font-semibold text-slate-950">This build cannot read the graph service yet</h3>
        <p class="mt-2 max-w-2xl text-sm leading-6 text-slate-700">{{.Message}} No placeholder resources are shown. The console will connect through its service adapter after the corrected backend contract lands.</p>
        <a href="/cloud" class="btn btn-secondary mt-5">Retry</a>
    </section>
    {{else}}
    <div class="grid gap-5 xl:grid-cols-2">
        <section id="networks" class="console-card rounded-[28px] p-6">
            <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Project scope</p><h3 class="mt-1 text-xl font-semibold">Networks → subnets</h3></div><button class="text-sm font-semibold text-[#2f6db5]" hx-get="/projects/{{.Context.Project.Slug}}/cloud/new?kind=subnet" hx-target="#modal-content">+ Subnet</button></div>
            <div class="mt-5 space-y-4">{{range .Graph.Networks}}
                <article id="network-{{.ID}}" class="rounded-2xl border border-slate-200 bg-white p-4">
                    <div class="flex items-start justify-between gap-3"><div><h4 class="font-semibold">{{.Name}}</h4><p class="mt-1 text-xs text-slate-500">{{.Region}}</p><div class="mt-2 flex items-center gap-2"><code class="text-[11px] text-slate-500">{{.ID}}</code><button class="text-[11px] font-semibold text-[#2f6db5]" onclick="copyGraphID('{{.ID}}', this)">Copy ID</button></div></div><button class="text-xs font-medium text-red-600" hx-delete="/projects/{{$.Context.Project.Slug}}/cloud/network/{{.ID}}" hx-target="#content" hx-confirm="Delete network {{.Name}}? Deletion is restricted while subnets exist; remove every child subnet first.">Delete</button></div>
                    <div class="ml-1 mt-4 border-l-2 border-blue-100 pl-4">{{range .Subnets}}
                        <div id="subnet-{{.ID}}" class="mb-2 rounded-xl bg-slate-50 p-3 last:mb-0"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-medium">{{.Name}}</p><p class="font-mono text-[11px] text-slate-500">{{.CIDR}}</p></div><button class="text-[11px] text-red-600" hx-delete="/projects/{{$.Context.Project.Slug}}/cloud/subnet/{{.ID}}" hx-target="#content" hx-confirm="Delete subnet {{.Name}}? Deletion is restricted while instances or load balancers reference this subnet.">Delete</button></div><div class="mt-2 flex flex-wrap gap-3 text-[11px] text-slate-500"><button class="font-semibold text-[#2f6db5]" onclick="copyGraphID('{{.ID}}', this)">Copy ID</button><span>{{.InstanceCount}} instances</span><span>{{.LBCount}} load balancers</span></div></div>
                    {{else}}<p class="rounded-xl bg-slate-50 p-3 text-xs text-slate-500">No subnets. Add the first child subnet to place instances or load balancers.</p>{{end}}</div>
                </article>
            {{else}}<div class="rounded-2xl border border-dashed border-slate-300 p-6 text-center"><p class="text-sm font-medium">No networks</p><p class="mt-1 text-xs text-slate-500">Create a regional network, then add non-overlapping private IPv4 subnets.</p></div>{{end}}</div>
        </section>

        <section id="load-balancers" class="console-card rounded-[28px] p-6">
            <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Project scope</p><h3 class="mt-1 text-xl font-semibold">Load balancers → backends</h3></div><button class="text-sm font-semibold text-[#2f6db5]" hx-get="/projects/{{.Context.Project.Slug}}/cloud/new?kind=backend" hx-target="#modal-content">+ Backend</button></div>
            <div class="mt-5 space-y-4">{{range .Graph.LoadBalancers}}
                <article id="load-balancer-{{.ID}}" class="rounded-2xl border border-slate-200 bg-white p-4"><div class="flex items-start justify-between gap-3"><div><div class="flex items-center gap-2"><h4 class="font-semibold">{{.Name}}</h4><span class="rounded-full bg-blue-50 px-2 py-0.5 text-[10px] font-bold uppercase text-blue-700">{{.Status}}</span></div><p class="mt-1 text-xs text-slate-500">{{.Protocol}} :{{.Port}} · {{.Algorithm}} · {{.Region}}</p><a href="#subnet-{{.SubnetID}}" class="mt-1 block text-xs font-medium text-[#2f6db5]">Subnet → {{.SubnetName}}</a><button class="mt-2 text-[11px] font-semibold text-[#2f6db5]" onclick="copyGraphID('{{.ID}}', this)">Copy ID</button></div><button class="text-xs text-red-600" hx-delete="/projects/{{$.Context.Project.Slug}}/cloud/load-balancer/{{.ID}}" hx-target="#content" hx-confirm="Delete load balancer {{.Name}}? Its backend edges will be deleted automatically; instances are not deleted.">Delete</button></div>
                    <div class="mt-4 grid gap-2 sm:grid-cols-2">{{range .Backends}}<div id="backend-{{.ID}}" class="rounded-xl bg-slate-50 p-3"><div class="flex items-center justify-between gap-2"><a href="#instance-{{.InstanceID}}" class="text-sm font-semibold text-[#2f6db5]">{{.InstanceName}}:{{.Port}}</a>{{if .Healthy}}<span class="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-semibold text-emerald-700">healthy</span>{{else}}<span class="rounded-full bg-red-100 px-2 py-0.5 text-[10px] font-semibold text-red-700">unhealthy</span>{{end}}</div><p class="mt-1 text-[11px] text-slate-500">Weight {{.Weight}} · {{if .Enabled}}enabled{{else}}disabled{{end}}</p><div class="mt-2 flex gap-3"><button class="text-[11px] font-semibold text-[#2f6db5]" onclick="copyGraphID('{{.ID}}', this)">Copy ID</button><button class="text-[11px] text-red-600" hx-delete="/projects/{{$.Context.Project.Slug}}/cloud/backend/{{.ID}}" hx-target="#content" hx-confirm="Remove this backend edge? The instance and load balancer will remain.">Remove edge</button></div></div>{{else}}<p class="rounded-xl bg-slate-50 p-3 text-xs text-slate-500">No backends. Health is computed as enabled and instance running; there is no active probe.</p>{{end}}</div>
                </article>
            {{else}}<div class="rounded-2xl border border-dashed border-slate-300 p-6 text-center"><p class="text-sm font-medium">No load balancers</p><p class="mt-1 text-xs text-slate-500">Load balancers and their instances must share a project and subnet.</p></div>{{end}}</div>
        </section>

        <section id="disks" class="console-card rounded-[28px] p-6">
            <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Project scope</p><h3 class="mt-1 text-xl font-semibold">Disks ↔ attachment</h3></div><div class="flex gap-3"><button class="text-sm font-semibold text-[#2f6db5]" hx-get="/projects/{{.Context.Project.Slug}}/cloud/new?kind=disk" hx-target="#modal-content">+ Disk</button><button class="text-sm font-semibold text-[#2f6db5]" hx-get="/projects/{{.Context.Project.Slug}}/cloud/new?kind=attachment" hx-target="#modal-content">+ Attach</button></div></div>
            <div class="mt-5 grid gap-3 sm:grid-cols-2">{{range .Graph.Disks}}<article id="disk-{{.ID}}" class="rounded-2xl border border-slate-200 bg-white p-4"><div class="flex justify-between gap-3"><div><h4 class="font-semibold">{{.Name}}</h4><p class="mt-1 text-xs text-slate-500">{{.SizeGB}} GiB {{.Type}} · {{.Region}}</p><button class="mt-2 text-[11px] font-semibold text-[#2f6db5]" onclick="copyGraphID('{{.ID}}', this)">Copy ID</button></div><button class="text-xs text-red-600" hx-delete="/projects/{{$.Context.Project.Slug}}/cloud/disk/{{.ID}}" hx-target="#content" hx-confirm="Delete disk {{.Name}}? Deletion is restricted while attached; remove its attachment first. Disk data is then permanently deleted.">Delete</button></div>{{with .Attachment}}<div class="mt-4 rounded-xl bg-blue-50 p-3"><p class="text-[10px] font-semibold uppercase tracking-wider text-blue-600">Single attachment</p><a href="#instance-{{.InstanceID}}" class="mt-1 block text-sm font-semibold text-blue-900">{{.InstanceName}} · {{.Device}}</a><div class="mt-2 flex gap-3"><button class="text-[11px] font-semibold text-blue-700" onclick="copyGraphID('{{.ID}}', this)">Copy edge ID</button><button class="text-[11px] text-red-600" hx-delete="/projects/{{$.Context.Project.Slug}}/cloud/attachment/{{.ID}}" hx-target="#content" hx-confirm="Delete this attachment edge? The disk and instance will both remain.">Detach</button></div></div>{{else}}<p class="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-500">Unattached. This disk can attach to one same-region instance.</p>{{end}}</article>{{else}}<p class="rounded-2xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500 sm:col-span-2">No disks in this project.</p>{{end}}</div>
        </section>

        <section id="policies" class="console-card rounded-[28px] p-6">
            <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-purple-600">Organization scope</p><h3 class="mt-1 text-xl font-semibold">Policies → binding graph</h3></div><div class="flex gap-3"><button class="text-sm font-semibold text-[#2f6db5]" hx-get="/projects/{{.Context.Project.Slug}}/cloud/new?kind=policy" hx-target="#modal-content">+ Policy</button><button class="text-sm font-semibold text-[#2f6db5]" hx-get="/projects/{{.Context.Project.Slug}}/cloud/new?kind=binding" hx-target="#modal-content">+ Binding</button></div></div>
            <p class="mt-2 text-xs text-slate-500">Policies belong to {{.Context.Org.Name}}. Bindings connect organization/API-key principals to same-organization targets; they do not enforce CRUD authorization.</p>
            <div class="mt-5 space-y-3">{{range .Graph.Policies}}<article id="policy-{{.ID}}" class="rounded-2xl border border-purple-100 bg-white p-4"><div class="flex justify-between gap-3"><div><div class="flex items-center gap-2"><h4 class="font-semibold">{{.Name}}</h4><span class="rounded bg-purple-50 px-2 py-0.5 text-[10px] font-bold uppercase text-purple-700">{{.Effect}}</span></div><p class="mt-1 text-xs text-slate-500">{{.Description}}</p><p class="mt-1 font-mono text-[11px] text-slate-500">Actions: {{range $i, $action := .Actions}}{{if $i}}, {{end}}{{$action}}{{end}}</p><button class="mt-2 text-[11px] font-semibold text-[#2f6db5]" onclick="copyGraphID('{{.ID}}', this)">Copy ID</button></div><button class="text-xs text-red-600" hx-delete="/projects/{{$.Context.Project.Slug}}/cloud/policy/{{.ID}}" hx-target="#content" hx-confirm="Delete organization policy {{.Name}}? Every binding owned by this policy will be deleted automatically.">Delete</button></div><div class="mt-3 space-y-2">{{range .Bindings}}<div class="rounded-xl bg-slate-50 p-3"><div class="flex items-start justify-between gap-3"><div><p class="text-sm"><strong>{{.PrincipalType}}:{{.PrincipalID}}</strong></p><a href="#{{.TargetType}}-{{.TargetID}}" class="text-xs font-medium text-[#2f6db5]">→ {{.TargetType}} / {{.TargetName}}</a></div><button class="text-[11px] text-red-600" hx-delete="/projects/{{$.Context.Project.Slug}}/cloud/binding/{{.ID}}" hx-target="#content" hx-confirm="Delete this immutable binding edge? The policy, principal, and target remain.">Remove edge</button></div><button class="mt-2 text-[11px] font-semibold text-[#2f6db5]" onclick="copyGraphID('{{.ID}}', this)">Copy edge ID</button></div>{{else}}<p class="rounded-xl bg-slate-50 p-3 text-xs text-slate-500">No bindings. This policy currently matches no principal-target edges.</p>{{end}}</div></article>{{else}}<p class="rounded-2xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">No organization policies.</p>{{end}}</div>
        </section>
    </div>

    <section id="instances" class="rounded-[28px] border border-slate-800 bg-slate-950 p-6 text-white shadow-xl">
        <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Project scope</p><h3 class="mt-1 text-xl font-semibold">Instance relationship detail</h3>
        <div class="mt-5 grid gap-4 lg:grid-cols-2">{{range .Graph.Instances}}<article id="instance-{{.ID}}" class="rounded-2xl border border-slate-700 bg-slate-900 p-4"><div class="flex items-start justify-between"><div><div class="flex items-center gap-2"><span class="h-2 w-2 rounded-full {{if eq .Status "running"}}bg-emerald-400{{else}}bg-slate-500{{end}}"></span><h4 class="font-semibold">{{.Name}}</h4></div><p class="mt-1 text-xs text-slate-400">{{.Region}} · {{.Status}}</p></div><button class="text-[11px] font-semibold text-blue-300" onclick="copyGraphID('{{.ID}}', this)">Copy ID</button></div><div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-slate-800 p-3"><p class="text-[10px] uppercase tracking-wider text-slate-500">Subnet</p>{{if .SubnetID}}<a href="#subnet-{{.SubnetID}}" class="mt-1 block text-sm font-medium text-blue-300">{{.SubnetName}}</a>{{else}}<p class="mt-1 text-xs text-slate-400">None</p>{{end}}</div><div class="rounded-xl bg-slate-800 p-3"><p class="text-[10px] uppercase tracking-wider text-slate-500">Attached disks</p>{{range .Disks}}<a href="#disk-{{.ID}}" class="mt-1 block text-sm text-blue-300">{{.Name}}</a>{{else}}<p class="mt-1 text-xs text-slate-400">None</p>{{end}}</div><div class="rounded-xl bg-slate-800 p-3"><p class="text-[10px] uppercase tracking-wider text-slate-500">LB membership</p>{{range .LoadBalancers}}<a href="#load-balancer-{{.ID}}" class="mt-1 block text-sm text-blue-300">{{.Name}}:{{.Port}} {{if .Healthy}}✓{{else}}×{{end}}</a>{{else}}<p class="mt-1 text-xs text-slate-400">None</p>{{end}}</div></div><p class="mt-3 text-[11px] leading-5 text-slate-400">Deleting this instance cascades its attachment edges, load-balancer backends, and policy bindings that target it. Disks survive.</p></article>{{else}}<p class="rounded-2xl border border-dashed border-slate-700 p-6 text-center text-sm text-slate-400 lg:col-span-2">No instances. Instance relationships appear here after compute resources exist.</p>{{end}}</div>
    </section>
    {{end}}

    <section id="fault-lab" class="rounded-[28px] border-2 border-dashed border-amber-300 bg-amber-50/80 p-6">
        <div class="flex items-center gap-2"><span class="rounded-md bg-amber-200 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-amber-900">Read only</span><h3 class="font-semibold text-slate-950">Fault Lab</h3></div>
        <p class="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Fault rules are organization-scoped API tooling. This console documents status only: writable controls remain disabled while organization permalinks grant writable browser sessions.</p>
        <div class="mt-4 grid gap-3 md:grid-cols-3"><div class="rounded-xl border border-amber-200 bg-white p-4"><p class="text-sm font-semibold">Management</p><p class="mt-1 text-xs leading-5 text-slate-600">Use authenticated API-key routes. Fault-management, web, static, build, organization-reset, and public organization routes are exempt from injection.</p></div><div class="rounded-xl border border-amber-200 bg-white p-4"><p class="text-sm font-semibold">Evaluation</p><p class="mt-1 text-xs leading-5 text-slate-600">The first enabled rule is selected by priority and ID. Match and trigger counters are persistent and deterministic.</p></div><div class="rounded-xl border border-amber-200 bg-white p-4"><p class="text-sm font-semibold">Effects</p><p class="mt-1 text-xs leading-5 text-slate-600">Bounded delay or configured HTTP status occurs before the handler. No virtual clock and no after-commit ambiguity.</p></div></div>
    </section>
</div>
<style>
.cloud-graph, .cloud-graph section, .cloud-graph article, .cloud-graph .grid > *, .cloud-graph .flex > * { min-width: 0; }
.cloud-graph article > .flex, .cloud-graph section > .flex { flex-wrap: wrap; }
.cloud-graph code, .cloud-graph strong, .cloud-graph .font-mono { overflow-wrap: anywhere; word-break: break-word; }
</style>
<script>function copyGraphID(id, button){if(navigator.clipboard){navigator.clipboard.writeText(id)}var label=button.textContent;button.textContent='Copied';setTimeout(function(){button.textContent=label},1200)}</script>
{{end}}`

const cloudGraphFormTemplate = `<div class="p-6">
    <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-[#2f6db5]">Cloud graph</p><h3 id="modal-title" class="mt-1 text-xl font-semibold capitalize">Create {{.Kind}}</h3></div><button type="button" aria-label="Close create {{.Kind}} dialog" class="text-2xl text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#2878B5]" onclick="closeModal()">×</button></div>
    {{if or (eq .Kind "policy") (eq .Kind "binding")}}<p class="mt-2 rounded-xl bg-purple-50 p-3 text-xs text-purple-800">Organization-scoped. Every principal and target must resolve within the current organization.</p>{{end}}
    <form class="mt-5 space-y-4" hx-post="/projects/{{.Project.Slug}}/cloud/resources" hx-target="#content"><input type="hidden" name="kind" value="{{.Kind}}"><div id="form-error" role="alert" aria-live="assertive" aria-atomic="true"></div>
        {{if or (eq .Kind "network") (eq .Kind "subnet") (eq .Kind "disk") (eq .Kind "policy") (eq .Kind "load-balancer")}}<label class="block text-sm font-medium">Name<input name="name" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label>{{end}}
        {{if eq .Kind "network"}}<label class="block text-sm font-medium">Region<select name="region" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option>us-east-1</option><option>us-west-1</option><option>eu-west-1</option><option>eu-central-1</option><option>ap-east-1</option></select></label>{{end}}
        {{if eq .Kind "subnet"}}<label class="block text-sm font-medium">Parent network<select name="parent_id" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5">{{range .Graph.Networks}}<option value="{{.ID}}">{{.Name}} · {{.Region}}</option>{{end}}</select></label><label class="block text-sm font-medium">Private IPv4 CIDR<input name="cidr" required value="10.0.1.0/24" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-mono"></label>{{end}}
        {{if eq .Kind "disk"}}<div class="grid grid-cols-1 gap-3 sm:grid-cols-3"><label class="min-w-0 text-sm font-medium">Size GiB<input name="size_gb" type="number" min="1" max="16384" value="100" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><label class="min-w-0 text-sm font-medium">Type<select name="disk_type" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option>standard</option><option>ssd</option></select></label><label class="min-w-0 text-sm font-medium">Region<input name="region" value="us-east-1" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label></div>{{end}}
        {{if eq .Kind "attachment"}}<label class="block text-sm font-medium">Disk<select name="parent_id" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5">{{range .Graph.Disks}}{{if not .Attachment}}<option value="{{.ID}}">{{.Name}} · {{.Region}}</option>{{end}}{{end}}</select></label><div class="grid grid-cols-1 gap-3 sm:grid-cols-2"><label class="text-sm font-medium">Instance<select name="instance_id" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5">{{range .Graph.Instances}}<option value="{{.ID}}">{{.Name}} · {{.Region}}</option>{{end}}</select></label><label class="text-sm font-medium">Device<input name="device" pattern="vd[b-z]" value="vdb" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-mono"></label></div>{{end}}
        {{if eq .Kind "policy"}}<label class="block text-sm font-medium">Description<input name="description" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><div class="grid grid-cols-1 gap-3 sm:grid-cols-2"><label class="text-sm font-medium">Effect<select name="effect" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option>allow</option><option>deny</option></select></label><label class="text-sm font-medium">Actions<input name="actions" value="*" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5" placeholder="*, or comma-separated exact operations"></label></div>{{end}}
        {{if eq .Kind "binding"}}<label class="block text-sm font-medium">Policy<select name="parent_id" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5">{{range .Graph.Policies}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><div class="grid grid-cols-1 gap-3 sm:grid-cols-2"><label class="text-sm font-medium">Principal type<select name="principal_type" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="organization">organization</option><option value="api_key">api_key</option></select></label><label class="text-sm font-medium">Principal ID<input name="principal_id" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-mono"></label></div><div class="grid grid-cols-1 gap-3 sm:grid-cols-2"><label class="text-sm font-medium">Target type<input name="target_type" required placeholder="project, network, subnet…" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><label class="text-sm font-medium">Target ID<input name="target_id" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-mono"></label></div>{{end}}
        {{if eq .Kind "load-balancer"}}<label class="block text-sm font-medium">Subnet<select name="subnet_id" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5">{{range .Graph.Networks}}{{range .Subnets}}<option value="{{.ID}}">{{.Name}} · {{.CIDR}}</option>{{end}}{{end}}</select></label><div class="grid grid-cols-1 gap-3 sm:grid-cols-3"><label class="text-sm font-medium">Protocol<select name="protocol" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option>http</option><option>tcp</option></select></label><label class="text-sm font-medium">Port<input name="port" type="number" min="1" max="65535" value="443" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><label class="text-sm font-medium">Algorithm<select name="algorithm" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option>round_robin</option><option>least_connections</option></select></label></div><label class="block text-sm font-medium">Health check path<input name="health_check_path" value="/healthz" class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-mono"></label>{{end}}
        {{if eq .Kind "backend"}}<label class="block text-sm font-medium">Load balancer<select name="parent_id" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5">{{range .Graph.LoadBalancers}}<option value="{{.ID}}">{{.Name}} · {{.SubnetName}}</option>{{end}}</select></label><div class="grid grid-cols-1 gap-3 sm:grid-cols-3"><label class="text-sm font-medium">Instance<select name="instance_id" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5">{{range .Graph.Instances}}<option value="{{.ID}}">{{.Name}} · {{.SubnetName}}</option>{{end}}</select></label><label class="text-sm font-medium">Port<input name="port" type="number" min="1" max="65535" value="8080" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><label class="text-sm font-medium">Weight<input name="weight" type="number" min="1" max="100" value="1" required class="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label></div><input type="hidden" name="enabled" value="true">{{end}}
        <div class="flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" class="btn btn-secondary" onclick="closeModal()">Cancel</button><button type="submit" class="btn btn-primary">Create</button></div>
    </form>
</div>`
